<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('items')->delete();

        \DB::table('items')->insert(array (
            0 =>
            array (
                'id' => 1,
                'category_id' => 1,
                'name' => 'sandwich au thon',
                'image' => 'https://menu.soukexpress.ma/storage/items/2a64c0a0-1301-4925-8072-7900e79427cb/1636820655.png',
                'description' => 'Thon Salade au goût',
                'price' => 14.0,
                'is_active' => 1,
                'level' => 1,
            ),
            1 =>
            array (
                'id' => 2,
                'category_id' => 1,
                'name' => 'Sandwichs à la viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/4e78d78d-6516-4b0e-b82d-4104a8cc9139/1638302653.jpg',
                'description' => 'viande hachée Salade au goût',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 4,
            ),
            2 =>
            array (
                'id' => 3,
                'category_id' => 1,
                'name' => 'Sandwichs Dand Fumi',
                'image' => 'https://menu.soukexpress.ma/storage/items/600038a4-f711-4c5a-a396-794a58f49b10/1636666482.jpg',
                'description' => 'Dand Fumi Salade au goût',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 2,
            ),
            3 =>
            array (
                'id' => 11,
                'category_id' => 22,
                'name' => 'CHICKEN BURGERS',
                'image' => 'https://menu.soukexpress.ma/storage/items/19403877-970d-4b23-82c7-e98da937b08c/1635607853.png',
                'description' => 'Filet de poitrine de poulet grillé à la flamme, garni d\'une salade fraîche et d\'une vinaigrette ranch crémeuse sur un petit pain aux graines de sésame grillé.',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            4 =>
            array (
                'id' => 12,
                'category_id' => 22,
                'name' => 'CHICKEN ROYALE',
                'image' => 'https://menu.soukexpress.ma/storage/items/7e3d5b6e-81aa-430a-8ddf-832df2ab63b8/1635617161.png',
                'description' => 'Royal Burger, on parle de poulet 100% croquant avec laitue et mayonnaise crémeuse.',
                'price' => 30.0,
                'is_active' => 1,
                'level' => 1,
            ),
            5 =>
            array (
                'id' => 13,
                'category_id' => 22,
                'name' => 'CHICKEN ROYALE DOUBLE CHEESE',
                'image' => 'https://menu.soukexpress.ma/storage/items/be12af5b-12d7-47fc-951c-dbf954b3d1a4/1635623820.png',
                'description' => 'Burger royal, on parle de poulet 100% croquant avec laitue, mayonnaise crémeuse et double cheddar',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            6 =>
            array (
                'id' => 14,
                'category_id' => 22,
                'name' => 'GRILLED CHICKEN WITH BACON & CHEESE',
                'image' => 'https://menu.soukexpress.ma/storage/items/631e7c28-b133-4e29-b37d-450a68b33627/1635624557.png',
                'description' => 'Filet de poitrine de poulet grillé garni de fromage fondu, bacon croustillant et salade fraîche avec vinaigrette ranch crémeuse sur pain aux graines de sésame grillé.',
                'price' => 55.0,
                'is_active' => 1,
                'level' => 1,
            ),
            7 =>
            array (
                'id' => 18,
                'category_id' => 1,
                'name' => 'Sandwichs aux œufs',
                'image' => 'https://menu.soukexpress.ma/storage/items/3bf31eca-b5ff-4267-b7a0-2f0f1702b4a4/1636823575.png',
                'description' => 'œufs pochés Salade selon le duc',
                'price' => 12.0,
                'is_active' => 1,
                'level' => 1,
            ),
            8 =>
            array (
                'id' => 19,
                'category_id' => 1,
                'name' => 'sandwich Kasher de dinde',
                'image' => 'https://menu.soukexpress.ma/storage/items/be292567-70c4-47bc-8153-977a36d3a31d/1636818096.jpg',
                'description' => 'Kasher de dinde Salade selon le duc',
                'price' => 12.0,
                'is_active' => 1,
                'level' => 1,
            ),
            9 =>
            array (
                'id' => 20,
                'category_id' => 25,
                'name' => 'Sauce tomate à la viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/00ebc99f-53f4-4622-b4c0-3720be5f1955/1637528072.jpg',
                'description' => 'viande hachée , Sauce bolognaise , basilic , parmesan',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            10 =>
            array (
                'id' => 21,
                'category_id' => 1,
                'name' => 'patatas sandwich',
                'image' => 'https://menu.soukexpress.ma/storage/items/fe677adb-d74b-432e-952f-61ed79d5cd47/1637011145.jpg',
                'description' => 'patatas Salade selon le duc',
                'price' => 15.0,
                'is_active' => 1,
                'level' => 1,
            ),
            11 =>
            array (
                'id' => 22,
                'category_id' => 1,
                'name' => 'Sandwich aux œufs frits',
                'image' => 'https://menu.soukexpress.ma/storage/items/d7afc02c-33c9-4f02-8406-c509393a7bd5/1637013662.jpg',
                'description' => 'aux œufs frits Salade selon le duc',
                'price' => 12.0,
                'is_active' => 1,
                'level' => 1,
            ),
            12 =>
            array (
                'id' => 23,
                'category_id' => 1,
                'name' => 'Sandwich au poulet Grillé',
                'image' => 'https://menu.soukexpress.ma/storage/items/dd78afea-2efd-41b3-8660-0bb3e3e7a754/1637014711.png',
                'description' => 'poulet Salade au goût',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 1,
            ),
            13 =>
            array (
                'id' => 24,
                'category_id' => 1,
                'name' => 'Sandwich à la mortadelle',
                'image' => 'https://menu.soukexpress.ma/storage/items/559cc181-e6bf-42f1-8dbd-74f481a086f8/1637015864.jpg',
                'description' => 'mortadelle',
                'price' => 12.0,
                'is_active' => 1,
                'level' => 1,
            ),
            14 =>
            array (
                'id' => 25,
                'category_id' => 1,
                'name' => 'Sandwich au foie',
                'image' => 'https://menu.soukexpress.ma/storage/items/cea76304-54f1-4c86-9aa6-7f65ff7ab68c/1637017342.png',
                'description' => 'Sandwich au foie',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            15 =>
            array (
                'id' => 26,
                'category_id' => 1,
                'name' => 'sandwich au poulet',
                'image' => 'https://menu.soukexpress.ma/storage/items/5b6d7435-c5e2-467f-9010-4956428119f6/1637086426.jpg',
                'description' => 'poulet',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 1,
            ),
            16 =>
            array (
                'id' => 27,
                'category_id' => 11,
                'name' => 'salade César',
                'image' => 'https://menu.soukexpress.ma/storage/items/dbb0852e-b740-40ac-a2a1-e2a35b8d2fa9/1637088040.jpg',
                'description' => 'filet de poulet,  salade batavia, pain sec, Tomates Cerises, oignons,Basilic, maïs, sauce césar, Fromage Parmesan, Huile d\'olive,le sel,vinaigre blanc',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            17 =>
            array (
                'id' => 28,
                'category_id' => 11,
                'name' => 'nicoise salad',
                'image' => 'https://menu.soukexpress.ma/storage/items/6b473d0a-bbb6-4190-bd79-0b48d89df6f7/1637092926.jpg',
                'description' => 'Thon,anchois,Tomate cerise,poivron rouge,concombre,haricots verts,œufs,oignon,olives noires,sauce mayo',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            18 =>
            array (
                'id' => 29,
                'category_id' => 11,
                'name' => 'Salade De Fruits De Mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/33702e36-2398-4d4f-80cb-9b636d07e9d4/1637098173.jpg',
                'description' => 'crevettes,calamare,lesmoules,surimi,tomate cerise,salade batavia,olives noires,champignons,basilic,',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            19 =>
            array (
                'id' => 30,
                'category_id' => 11,
                'name' => 'salade marocaine',
                'image' => 'https://menu.soukexpress.ma/storage/items/2f483808-79d4-4394-a81e-6abf3d66a27f/1637172098.jpg',
                'description' => 'Thon,Tomate cerise,poivron ver,concombre,oignon,salade batavia,Sauce Vinaigrette,',
                'price' => 15.0,
                'is_active' => 1,
                'level' => 4,
            ),
            20 =>
            array (
                'id' => 31,
                'category_id' => 11,
                'name' => 'chief\'s salad',
                'image' => 'https://menu.soukexpress.ma/storage/items/c6f27ad2-407e-418b-81f8-ef96c579a3e9/1637174401.jpg',
                'description' => 'œufs maïs Thon  avocat  carottes  concombre  riz  Pomme  crevettes  fromage  parmesan  sauce  cocktail',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 5,
            ),
            21 =>
            array (
                'id' => 32,
                'category_id' => 27,
                'name' => 'Grill Overlords Angus, & Cheese',
                'image' => 'https://menu.soukexpress.ma/storage/items/37ba131a-8d8e-46e7-a7e1-f0ffe4f76f4f/1637176910.png',
                'description' => 'Boeuf Angus grillé à la flamme, sur pain brioché. Ajoutez ensuite du fromage cheddar et du bœuf fu philly avec une sauce barbecue fumée et des cornichons.',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            22 =>
            array (
                'id' => 33,
                'category_id' => 27,
                'name' => 'Grill Overlord Chicago Angus',
                'image' => 'https://menu.soukexpress.ma/storage/items/21ac6167-5c56-486e-b24d-6e30ac36c5d7/1637181904.png',
                'description' => 'Boeuf Angus grillé à la flamme avec pain brioché. Ajoutez ensuite le fromage cheddar et le bœuf avec la sauce barbecue fumée et les cornichons.',
                'price' => 60.0,
                'is_active' => 1,
                'level' => 2,
            ),
            23 =>
            array (
                'id' => 34,
                'category_id' => 27,
                'name' => 'Grill Overlords Double Angus, Cheese',
                'image' => 'https://menu.soukexpress.ma/storage/items/35a5a607-f0e3-4027-9ce6-84a7648a89b9/1637183138.png',
                'description' => 'Deux morceaux de bœuf haché à la marocaine avec du pain burtouch et du double cheddar. Recouvert de sauce BBQ fumée et de cornichons.',
                'price' => 100.0,
                'is_active' => 1,
                'level' => 5,
            ),
            24 =>
            array (
                'id' => 35,
                'category_id' => 27,
                'name' => 'Grill Overlords  BBQ Onion is crunchy',
                'image' => 'https://menu.soukexpress.ma/storage/items/3f8bdf89-fe30-457d-be4a-340e15a41274/1637185277.png',
                'description' => 'Un morceau de boeuf haché marocain avec du pain brittoush et du double cheddar. Nappé de sauce BBQ fumée, cornichons, oignons croquants et mayonnaise',
                'price' => 55.0,
                'is_active' => 1,
                'level' => 3,
            ),
            25 =>
            array (
                'id' => 36,
                'category_id' => 27,
                'name' => 'Angus Overlords',
                'image' => 'https://menu.soukexpress.ma/storage/items/46fd1a8f-79c5-4517-a61c-217640d03759/1637186643.png',
                'description' => 'Un morceau de viande de qualité supérieure avec du bœuf haché marocain, du pain brittoush et du double cheddar. Couvert de sauce BBQ fumée et cornichons à la mayonnaise',
                'price' => 100.0,
                'is_active' => 1,
                'level' => 4,
            ),
            26 =>
            array (
                'id' => 37,
                'category_id' => 23,
                'name' => 'Shawarma Chicken Danders',
                'image' => 'https://menu.soukexpress.ma/storage/items/163d72c0-a4e4-40f7-8a04-b14e31a6e434/1637247553.jpg',
                'description' => 'Poulet Dandres ,laitue , tomate , Mayonnaise à l\'ail',
                'price' => 30.0,
                'is_active' => 1,
                'level' => 1,
            ),
            27 =>
            array (
                'id' => 38,
                'category_id' => 23,
                'name' => 'poulet shawarma',
                'image' => 'https://menu.soukexpress.ma/storage/items/d867742d-20d6-4f17-89a6-f6d6e797cd0f/1637253102.jpg',
                'description' => 'poulet , laitue , tomate , oignon , Mayonnaise à l\'ail',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 1,
            ),
            28 =>
            array (
                'id' => 39,
                'category_id' => 23,
                'name' => 'Shawarma au poulet et au fromage',
                'image' => 'https://menu.soukexpress.ma/storage/items/149175a8-28b9-4ba2-9358-48c9a0f40145/1637254036.jpg',
                'description' => 'poulet , ,laitue , tomate , oignon , fromage , Mayonnaise à l\'ail',
                'price' => 28.0,
                'is_active' => 1,
                'level' => 1,
            ),
            29 =>
            array (
                'id' => 40,
                'category_id' => 23,
                'name' => 'Shawarma au poulet dans du pain',
                'image' => 'https://menu.soukexpress.ma/storage/items/494ac3a2-f624-4390-a4d1-2aa7905e495c/1637254530.jpg',
                'description' => 'poulet , laitue , tomate , oignon , Mayonnaise à l\'ail',
                'price' => 30.0,
                'is_active' => 1,
                'level' => 1,
            ),
            30 =>
            array (
                'id' => 41,
                'category_id' => 23,
                'name' => 'Mix Shawarma',
                'image' => 'https://menu.soukexpress.ma/storage/items/0df46aeb-6dfa-4bc9-a83e-678d87b62a98/1637255217.jpg',
                'description' => 'viande hachée , poulet , laitue , tomate , oignon , Mayonnaise à l\'ail',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 6,
            ),
            31 =>
            array (
                'id' => 42,
                'category_id' => 23,
                'name' => 'Shawarma sans frites',
                'image' => 'https://menu.soukexpress.ma/storage/items/10392b51-6fc4-4db6-a685-125d7516963c/1637255913.jpg',
                'description' => 'poulet , laitue , tomate , oignon , Mayonnaise à l\'ail',
                'price' => 20.0,
                'is_active' => 1,
                'level' => 1,
            ),
            32 =>
            array (
                'id' => 43,
                'category_id' => 35,
                'name' => 'Pizza au poulet',
                'image' => 'https://menu.soukexpress.ma/storage/items/4cf64c08-3bf3-4adc-90f2-63ef7b596a8d/1637262876.jpg',
                'description' => 'poulet ,  mozzarella cheese % , sauce Tomate , champignons , olives noires , basilic',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 2,
            ),
            33 =>
            array (
                'id' => 44,
                'category_id' => 35,
                'name' => 'Pizza à la viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/ec1a1a66-c948-4d13-bc21-1a8963813188/1637265712.jpg',
                'description' => 'viande hachée ,  mozzarella cheese % , sauce Tomate , olives noires ,  basilic',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            34 =>
            array (
                'id' => 45,
                'category_id' => 35,
                'name' => 'pizza au thon',
                'image' => 'https://menu.soukexpress.ma/storage/items/b3d55335-1bd9-4ee1-8138-662d8a1792a3/1637266173.jpg',
                'description' => 'Thon , mozzarella cheese % , sauce Tomate , champignons , oignon , olives noires , basilic',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 6,
            ),
            35 =>
            array (
                'id' => 46,
                'category_id' => 35,
                'name' => 'Pizza Royale',
                'image' => 'https://menu.soukexpress.ma/storage/items/76f3c03a-26e6-48c2-9408-45ec0a4809b7/1637266486.jpg',
                'description' => 'les fruits de mer , viande hachée , Thon , poulet ,  mozzarella cheese % , sauce Tomate , champignons , olives noires , basilic',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 4,
            ),
            36 =>
            array (
                'id' => 47,
                'category_id' => 35,
                'name' => 'Pizza Margarita',
                'image' => 'https://menu.soukexpress.ma/storage/items/13e12e23-7754-4e12-89e7-4068fcc9a810/1637271552.jpg',
                'description' => 'mozzarella cheese % , sauce Tomate ,  olives noires , basilic',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 7,
            ),
            37 =>
            array (
                'id' => 49,
                'category_id' => 35,
                'name' => 'Pizza Quatre Saisons',
                'image' => 'https://menu.soukexpress.ma/storage/items/6788d239-646a-4fed-85c9-198b33635692/1637274384.jpg',
                'description' => 'Légumes , viande hachée , Thon , poulet ,  mozzarella cheese % , sauce Tomate , champignons , olives noires , basilic',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 12,
            ),
            38 =>
            array (
                'id' => 50,
                'category_id' => 35,
                'name' => 'pizza chorizo',
                'image' => 'https://menu.soukexpress.ma/storage/items/71feba95-0126-487e-bd1e-b8a1957886f2/1637271988.jpg',
                'description' => 'chorizo , mozzarella cheese % , sauce Tomate , champignons , basilic',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 9,
            ),
            39 =>
            array (
                'id' => 51,
                'category_id' => 35,
                'name' => 'Pizza Végétarien',
                'image' => 'https://menu.soukexpress.ma/storage/items/dcc872fb-caf4-4f1c-8515-42e000cb595b/1637272392.jpg',
                'description' => 'mozzarella cheese % , parmesan cheese , sauce Tomate , champignons , olives noires ,  artichaut , tomate , aubergine , courgette , pesto sauce , origan',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 11,
            ),
            40 =>
            array (
                'id' => 52,
                'category_id' => 35,
                'name' => 'Pizza aux quatre fromages',
                'image' => 'https://menu.soukexpress.ma/storage/items/fc819a67-7e06-4ea4-8bc1-4a6e98cab976/1637273565.jpg',
                'description' => 'mozzarella cheese % , sauce Tomate , fromage de chèvre , fromage bleu , fromage cheddar',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 5,
            ),
            41 =>
            array (
                'id' => 53,
                'category_id' => 35,
                'name' => 'Pizza aux fruits de mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/eb0f60a9-9131-4723-b185-7cd4ac4aab0d/1637351575.jpg',
                'description' => 'mozzarella cheese % , sauce Tomate , crevette , Clamar , palourde , moules , origan',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 3,
            ),
            42 =>
            array (
                'id' => 55,
                'category_id' => 35,
                'name' => 'pizza italiana',
                'image' => 'https://menu.soukexpress.ma/storage/items/a1339351-8037-4501-95da-07d94d6ec875/1637349858.jpg',
                'description' => 'jumbo de dinde , mozzarella cheese % , sauce Tomate , champignons , basilic , parmesan cheese',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 13,
            ),
            43 =>
            array (
                'id' => 56,
                'category_id' => 35,
                'name' => 'pizza au saumon',
                'image' => 'https://menu.soukexpress.ma/storage/items/d2267f93-1730-406f-b4bd-d57886ac57ee/1637351371.jpg',
                'description' => 'saumon fumé , artichaut , fromage mozzarella , olives vertes , basilic',
                'price' => 65.0,
                'is_active' => 1,
                'level' => 14,
            ),
            44 =>
            array (
                'id' => 57,
                'category_id' => 3,
                'name' => 'tacos à la viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/794b23cd-f007-4b75-8af4-cad5573ac34a/1637354959.jpg',
                'description' => 'viande hachée , sauce au fromage ,  Quelques pommes de terre sautées , Sauce algérienne ou sauce andalouse par choix',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            45 =>
            array (
                'id' => 58,
                'category_id' => 3,
                'name' => 'Tacos au poulet',
                'image' => 'https://menu.soukexpress.ma/storage/items/68c1507c-12e8-4fdd-a0da-0ab5ff47e00c/1637355075.jpg',
                'description' => 'poulet , sauce au fromage ,  Quelques pommes de terre sautées , Sauce algérienne ou sauce andalouse par choix',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            46 =>
            array (
                'id' => 59,
                'category_id' => 3,
                'name' => 'Tacos Cordon Bleu',
                'image' => 'https://menu.soukexpress.ma/storage/items/3c378926-53f6-4b27-81d7-2e9bbeae7386/1637356681.jpg',
                'description' => 'Cordon Bleu , sauce au fromage ,  Quelques pommes de terre sautées , Sauce algérienne ou sauce andalouse par choix',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            47 =>
            array (
                'id' => 60,
                'category_id' => 3,
                'name' => 'Tacos Mixtes',
                'image' => 'https://menu.soukexpress.ma/storage/items/80826bef-009c-4aae-8dfc-e5a361ab1875/1637357337.jpg',
                'description' => 'Viande hachée avec de la viande de poulet , sauce au fromage ,  Quelques pommes de terre sautées , Sauce algérienne ou sauce andalouse par choix',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            48 =>
            array (
                'id' => 61,
                'category_id' => 3,
                'name' => 'tacos nuggets',
                'image' => 'https://menu.soukexpress.ma/storage/items/a4226759-4d61-4643-a3df-1b22d3b60699/1637426152.jpg',
                'description' => 'nuggets  , sauce au fromage ,  Quelques pommes de terre sautées , Sauce algérienne ou sauce andalouse par choix',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            49 =>
            array (
                'id' => 62,
                'category_id' => 3,
                'name' => 'tacos aux crevettes',
                'image' => 'https://menu.soukexpress.ma/storage/items/02943f22-12d0-4858-849d-15b35e9853a0/1637438492.jpg',
                'description' => 'crevettes , sauce au fromage ,  Quelques pommes de terre sautées , Sauce algérienne ou sauce andalouse par choix',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 1,
            ),
            50 =>
            array (
                'id' => 63,
                'category_id' => 35,
                'name' => 'pepperoni pizza',
                'image' => 'https://menu.soukexpress.ma/storage/items/0c80a17c-78db-4dbd-af26-3169ab55b45d/1637444518.jpg',
                'description' => 'pepperoni , sauce tomate , fromage mozzarella , oignon blanc , l\'ail , basilic , sel , Le poivre noir',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 10,
            ),
            51 =>
            array (
                'id' => 64,
                'category_id' => 3,
                'name' => 'Tacos aux fruits de mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/cff028ed-800c-44e0-8eee-71aa8885429e/1637518380.jpg',
                'description' => 'crevette , Clamar , surimi , champignons , sauce au fromage ,  Quelques pommes de terre sautées ,',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            52 =>
            array (
                'id' => 65,
                'category_id' => 3,
                'name' => 'tacos Dandras au poulet',
                'image' => 'https://menu.soukexpress.ma/storage/items/ae0505c8-d73d-455b-bde1-2fdb6e4bc1d3/1637524220.jpg',
                'description' => 'Dandras au poulet , sauce au fromage ,  Quelques pommes de terre sautées , Sauce algérienne ou sauce andalouse par choix',
                'price' => 38.0,
                'is_active' => 1,
                'level' => 1,
            ),
            53 =>
            array (
                'id' => 66,
                'category_id' => 25,
                'name' => 'Spaghettis Aux Fruits De Mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/bebf609c-fa46-41e9-9bef-9828c821ae91/1637528273.jpg',
                'description' => 'surimi , calmar , crevettes , les moules polepe , basilic , parmesan , Sauce blanche',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 2,
            ),
            54 =>
            array (
                'id' => 67,
                'category_id' => 25,
                'name' => 'Spaghettis de fruits de mer à la sauce tomate',
                'image' => 'https://menu.soukexpress.ma/storage/items/ae5f725d-f44e-4b72-872d-b3b2ca5ab11b/1637529636.jpg',
                'description' => 'surimi , calmar , crevettes , les moules polepe , basilic , parmesan , Sauce blanche , sauce tomate',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 3,
            ),
            55 =>
            array (
                'id' => 68,
                'category_id' => 25,
                'name' => 'tagliatelle les fruits de mer Sauce blanche',
                'image' => 'https://menu.soukexpress.ma/storage/items/4d2c2d8b-99a2-4ec6-8727-05943f4e8571/1637531813.jpg',
                'description' => 'surimi , calmar , crevettes , les moules polepe , basilic , parmesan , Sauce blanche',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 5,
            ),
            56 =>
            array (
                'id' => 69,
                'category_id' => 25,
                'name' => 'tagliatelle de fruits de mer à la sauce tomate',
                'image' => 'https://menu.soukexpress.ma/storage/items/e58b2fb2-e5e8-4df3-83e6-24d38b9323d6/1637532881.jpg',
                'description' => 'surimi , calmar , crevettes , les moules polepe , basilic , parmesan , sauce tomate',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 6,
            ),
            57 =>
            array (
                'id' => 70,
                'category_id' => 25,
                'name' => 'tagliatelle viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/08e0142e-4418-4525-9f89-d4192d1ea100/1637533463.jpg',
                'description' => 'viande hachée , Sauce bolognaise , basilic , parmesan',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 2,
            ),
            58 =>
            array (
                'id' => 71,
                'category_id' => 24,
                'name' => 'Wrap viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/44170cb2-3d96-41d5-b421-600da3d6f7b6/1637615324.jpg',
                'description' => 'viande hachée , salade batavia , tomates , Cornichon , Sauce algérienne ou sauce andalouse par choix',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            59 =>
            array (
                'id' => 72,
                'category_id' => 24,
                'name' => 'Nugget wraps',
                'image' => 'https://menu.soukexpress.ma/storage/items/54ef30fe-5393-4c32-84d7-6d470388db33/1637615876.jpg',
                'description' => 'Nugget , salade batavia , tomates , Cornichon , Sauce algérienne ou sauce andalouse par choix',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            60 =>
            array (
                'id' => 73,
                'category_id' => 24,
                'name' => 'Cordon Bleu Wraps',
                'image' => 'https://menu.soukexpress.ma/storage/items/fd5bcd6c-67f9-4529-8ff4-e49278ae505c/1637616521.jpg',
                'description' => 'Cordon Bleu , salade batavia , tomates , Cornichon , Sauce algérienne ou sauce andalouse par choix',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            61 =>
            array (
                'id' => 74,
                'category_id' => 24,
                'name' => 'Wraps au poulet grillé sauce pili pili',
                'image' => 'https://menu.soukexpress.ma/storage/items/6e4d1102-863a-4ac0-9c25-a259ce985159/1637616739.jpg',
                'description' => 'poulet grillé , salade batavia , tomates , Cornichon , sauce pili pili , Sauce algérienne ou sauce andalouse par choix',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            62 =>
            array (
                'id' => 75,
                'category_id' => 24,
                'name' => 'wrap au poulet',
                'image' => 'https://menu.soukexpress.ma/storage/items/305025e5-ff73-48aa-b55a-cf5d28f3f631/1637617020.jpg',
                'description' => 'poulet , salade batavia , tomates , Cornichon , Sauce algérienne ou sauce andalouse par choix',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            63 =>
            array (
                'id' => 76,
                'category_id' => 24,
                'name' => 'Wraps Tenders de poulet',
                'image' => 'https://menu.soukexpress.ma/storage/items/d2f72acb-0ba4-4f72-8f93-ba38c0230fa9/1637617176.jpg',
                'description' => 'Tenders de poulet , salade batavia , tomates , Cornichon , Sauce algérienne ou sauce andalouse par choix',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            64 =>
            array (
                'id' => 77,
                'category_id' => 24,
                'name' => 'wraps fruits de mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/fb045b45-f5d6-4b89-9c3c-cc0714d9b072/1637618004.jpg',
                'description' => 'fruits de mer , salade batavia , tomates , Cornichon , Sauce algérienne ou sauce andalouse par choix',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            65 =>
            array (
                'id' => 78,
                'category_id' => 24,
                'name' => 'Mixte Wraps',
                'image' => 'https://menu.soukexpress.ma/storage/items/9746f9ea-25f7-4202-a3f2-e1a154b59129/1637618701.jpg',
                'description' => 'Mixte , salade batavia , tomates , Cornichon , Sauce algérienne ou sauce andalouse par choix',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            66 =>
            array (
                'id' => 79,
                'category_id' => 32,
                'name' => 'boissons chaudes',
                'image' => 'https://menu.soukexpress.ma/storage/items/cea204ee-a625-41d4-9786-c3e3cbadc200/1637689397.jpg',
                'description' => 'coffee',
                'price' => 1.0,
                'is_active' => 1,
                'level' => 1,
            ),
            67 =>
            array (
                'id' => 80,
                'category_id' => 25,
                'name' => 'Tagliatel aux saumon',
                'image' => 'https://menu.soukexpress.ma/storage/items/1d673781-14c1-463f-8de2-a74c413a0a02/1637700674.jpg',
                'description' => 'saumon , Crème fraîche , tomate cerise',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 1,
            ),
            68 =>
            array (
                'id' => 81,
                'category_id' => 25,
                'name' => 'spaghettis primavera',
                'image' => 'https://menu.soukexpress.ma/storage/items/4b1aad6d-2eca-4019-9726-520349fec261/1637787064.jpg',
                'description' => 'légumes vegetarien , crème fraiche',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 4,
            ),
            69 =>
            array (
                'id' => 82,
                'category_id' => 25,
                'name' => 'viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/a449cbf5-a27d-4443-8786-9678d887a883/1637706426.jpg',
                'description' => 'viande hachée , sauce tomate , le fromage',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 35,
            ),
            70 =>
            array (
                'id' => 83,
                'category_id' => 25,
                'name' => 'Lasagne les fruits de mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/f3b2f615-f8eb-40b5-895a-db51c93a0902/1637781934.jpg',
                'description' => 'surimi , calmar , crevettes , les moules polepe , basilic , parmesan , sauce tomate',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 21,
            ),
            71 =>
            array (
                'id' => 84,
                'category_id' => 25,
                'name' => 'Pasticcio poulet',
                'image' => 'https://menu.soukexpress.ma/storage/items/17c1d2fe-1a71-4219-9259-d56f584a75e2/1637785993.jpg',
                'description' => 'poulet , fromage , Quelques pommes de terre sautées , Penne',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 36,
            ),
            72 =>
            array (
                'id' => 85,
                'category_id' => 25,
                'name' => 'Pasticcio viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/58971149-8bdf-457f-a714-1235abcedf72/1637786098.jpg',
                'description' => 'viande hachée , fromage , Quelques pommes de terre sautées , Penne',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 43,
            ),
            73 =>
            array (
                'id' => 86,
                'category_id' => 25,
                'name' => 'Pasticcio Fruits De Mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/12557450-8ae6-4861-9e3c-7cdd1a07551a/1637786197.jpg',
                'description' => 'Pasticcio Fruits De Mer',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 57,
            ),
            74 =>
            array (
                'id' => 87,
                'category_id' => 25,
                'name' => 'Penne Pâtes au thon',
                'image' => 'https://menu.soukexpress.ma/storage/items/12750a28-b583-4202-aa2a-6bc9d88f6724/1637789083.jpg',
                'description' => 'Penne Pâtes au thon',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 33,
            ),
            75 =>
            array (
                'id' => 88,
                'category_id' => 25,
                'name' => 'penne pâtes au sauce tomate',
                'image' => 'https://menu.soukexpress.ma/storage/items/939d971e-6fdb-46d9-ba87-1a888b53f9bc/1637789260.jpg',
                'description' => 'penne pâtes au sauce tomate',
                'price' => 30.0,
                'is_active' => 1,
                'level' => 34,
            ),
            76 =>
            array (
                'id' => 89,
                'category_id' => 25,
                'name' => 'penne pâtes au viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/fab1bfa9-f0b6-4c55-b1bc-0c1725c46a31/1637789753.jpg',
                'description' => 'penne pâtes au viande hachée',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 37,
            ),
            77 =>
            array (
                'id' => 90,
                'category_id' => 25,
                'name' => 'penne pâtes au fruits de mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/17e1cd14-a14d-486f-92a3-1470ad6aa375/1637789624.jpg',
                'description' => 'Penne fruits de mer',
                'price' => 50.0,
                'is_active' => 1,
                'level' => 43,
            ),
            78 =>
            array (
                'id' => 91,
                'category_id' => 25,
                'name' => 'penne pâtes au poulet',
                'image' => 'https://menu.soukexpress.ma/storage/items/d3e0630d-28c1-4a02-848f-df2269e43944/1637845155.jpg',
                'description' => 'penne pâtes au poulet',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            79 =>
            array (
                'id' => 92,
                'category_id' => 7,
                'name' => 'whopper sellam',
                'image' => 'https://menu.soukexpress.ma/storage/items/58f7c6db-27f5-40e4-877b-5320be1b0471/1637847852.png',
                'description' => 'viande hachée , Chargé de laitue fraîche croustillante, d\'œufs au plat, de tomates mûres, d\'oignons, de cornichons, de mayo et de sauce tomate sur un petit pain aux graines de sésame grillé.',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            80 =>
            array (
                'id' => 93,
                'category_id' => 7,
                'name' => 'whopper Bacon',
                'image' => 'https://menu.soukexpress.ma/storage/items/5628f917-c8bd-4818-8851-013268f4cd51/1637851248.png',
                'description' => 'Un morceau de boeuf 100% marocain grillé sur la flamme avec deux tranches de fromage, steak, tomates, laitue, cornichons, oignons, mayonnaise et sauce tomate sur un pain aux graines de sésame grillé.',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            81 =>
            array (
                'id' => 94,
                'category_id' => 7,
                'name' => 'whopper cheese',
                'image' => 'https://menu.soukexpress.ma/storage/items/8b2e4abe-aeeb-4e9c-85c2-3e07d11e47fa/1637851780.png',
                'description' => 'Fromage Whopper avec du bœuf 100% marocain, garni de fromage fondu, de cornichons et de salade fraîche sur un petit pain aux graines de sésame grillé.',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            82 =>
            array (
                'id' => 95,
                'category_id' => 7,
                'name' => 'bacon de luxe',
                'image' => 'https://menu.soukexpress.ma/storage/items/05fb5e5c-6613-4ee3-ba37-0ce5fbe7ca2e/1637852026.png',
                'description' => 'Deux Morceaux De Boeuf 100% Marocain Grillé Sur La Flamme Avec Deux Tranches De Fromage, Steak De Boeuf, Tomates, Laitue, Cornichons, Oignons, Mayonnaise Et Sauce Tomate Sur Des Graines De Sésame Grillées.',
                'price' => 55.0,
                'is_active' => 1,
                'level' => 1,
            ),
            83 =>
            array (
                'id' => 96,
                'category_id' => 7,
                'name' => 'double whopper',
                'image' => 'https://menu.soukexpress.ma/storage/items/bfce762b-f7e9-48b8-888c-bc3ddd17b408/1637852236.png',
                'description' => 'Deux Morceaux De Boeuf 100% Marocain Grillé Sur Flamme, Steak, Tomates, Laitue, Cornichons, Oignons, Mayonnaise Et Sauce Tomate Sur Graines De Sésame Grillées.',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            84 =>
            array (
                'id' => 97,
                'category_id' => 7,
                'name' => 'whopper junior',
                'image' => 'https://menu.soukexpress.ma/storage/items/a7a65c48-4884-4de0-80e7-b2b3c7550dcb/1637852777.png',
                'description' => 'Waper, de petite taille. Le même bœuf marocain grillé à la flamme avec des tomates mûres, de la laitue fraîche, des oignons, des cornichons, de la mayonnaise et de la sauce tomate sur un petit pain aux graines de sésame grillé.',
                'price' => 23.0,
                'is_active' => 0,
                'level' => 1,
            ),
            85 =>
            array (
                'id' => 98,
                'category_id' => 26,
                'name' => 'poulet panini',
                'image' => 'https://menu.soukexpress.ma/storage/items/b322a955-817a-4ec9-945b-a5462720e5ce/1637860845.jpg',
                'description' => 'poulet  salade batavia  tomate  Mayonnaise à l\'ail  fromage mozzarella',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 1,
            ),
            86 =>
            array (
                'id' => 99,
                'category_id' => 26,
                'name' => 'panini thon',
                'image' => 'https://menu.soukexpress.ma/storage/items/99c5e30c-a76b-4d59-b40c-1e0e128c4053/1637857910.jpg',
                'description' => 'thon   salade batavia  tomate  Mayonnaise à l\'ail  fromage mozzarella',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 1,
            ),
            87 =>
            array (
                'id' => 100,
                'category_id' => 26,
                'name' => 'Panini Filet de dinde cuit fumé',
                'image' => 'https://menu.soukexpress.ma/storage/items/be54c61a-9860-4ae7-9a5e-c6f2eb97e938/1637861420.jpg',
                'description' => 'dinde cuit fumé  salade batavia  tomate  Mayonnaise à l\'ail  fromage mozzarella',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 1,
            ),
            88 =>
            array (
                'id' => 101,
                'category_id' => 26,
                'name' => 'panini salmon',
                'image' => 'https://menu.soukexpress.ma/storage/items/7483ce2c-417b-44b7-a0b5-b36d2429de0b/1637861207.jpg',
                'description' => 'salmon  salade batavia  tomate  Mayonnaise à l\'ail  fromage mozzarella',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            89 =>
            array (
                'id' => 102,
                'category_id' => 26,
                'name' => 'Chicken Tenders',
                'image' => 'https://menu.soukexpress.ma/storage/items/162f0f97-f85f-4629-903b-927ed97484d0/1637870386.jpg',
                'description' => 'Chicken Tenders  salade batavia  tomate  Mayonnaise à l\'ail  fromage mozzarella',
                'price' => 28.0,
                'is_active' => 1,
                'level' => 1,
            ),
            90 =>
            array (
                'id' => 103,
                'category_id' => 26,
                'name' => 'Panini de fruits de mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/4afac69b-80cd-41dc-9587-8a3083ef1208/1637876642.jpg',
                'description' => 'crevette  Clamar  surimi  champignons  sauce au fromage  salade batavia  tomate Mayonnaise à l\'ail  fromage mozzarella',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            91 =>
            array (
                'id' => 104,
                'category_id' => 26,
                'name' => 'Panini aux crevettes',
                'image' => 'https://menu.soukexpress.ma/storage/items/9146912b-c7fb-44e3-b829-95dcfcb8e6e3/1637879355.jpg',
                'description' => 'crevettes salade batavia tomate Mayonnaise à l\'ail fromage mozzarella',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            92 =>
            array (
                'id' => 105,
                'category_id' => 26,
                'name' => 'panini viande hachée',
                'image' => 'https://menu.soukexpress.ma/storage/items/6bc03df0-3872-486e-b036-211038d5dd13/1637879894.jpg',
                'description' => 'viande hachée salade batavia tomate Mayonnaise à l\'ail fromage mozzarella',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 1,
            ),
            93 =>
            array (
                'id' => 106,
                'category_id' => 26,
                'name' => 'Panini Mixte',
                'image' => 'https://menu.soukexpress.ma/storage/items/a0e1913e-85e8-455c-991d-a6ed244db2bd/1637881786.jpg',
                'description' => 'poulet viande hachée salade batavia tomate Mayonnaise à l\'ail fromage mozzarella',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            94 =>
            array (
                'id' => 107,
                'category_id' => 26,
                'name' => 'panini mozzarella',
                'image' => 'https://menu.soukexpress.ma/storage/items/cf18f8af-8bc9-411d-aece-ddcdc851f026/1637882638.jpg',
                'description' => 'mozzarella',
                'price' => 20.0,
                'is_active' => 1,
                'level' => 1,
            ),
            95 =>
            array (
                'id' => 108,
                'category_id' => 14,
                'name' => 'double cheese manchegas',
                'image' => 'https://menu.soukexpress.ma/storage/items/08cfcb80-b68e-4b3d-b134-980a6fcc84b3/1638570025.png',
                'description' => 'Deux Morceaux D\'Agneau 100% Grillés À La Flamme, Deux Tranches De Fromage, Cornichons, Moutarde Et Sauce Tomate Sur Toast De Graines De Sésame Grillées',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            96 =>
            array (
                'id' => 109,
                'category_id' => 14,
                'name' => 'manchegas',
                'image' => 'https://menu.soukexpress.ma/storage/items/ea17e779-00c4-45f7-b5c0-3bcbacdf19f5/1637959071.png',
                'description' => 'Agneau marocain grillé à la flamme, garni de cornichons croquants, de moutarde et de sauce tomate, servi dans du pain frais avec des graines de sésame grillées.',
                'price' => 30.0,
                'is_active' => 1,
                'level' => 1,
            ),
            97 =>
            array (
                'id' => 110,
                'category_id' => 14,
                'name' => 'BBQ cheese manchegas',
                'image' => 'https://menu.soukexpress.ma/storage/items/1b89bde6-0850-4691-becc-343d5e4b41d7/1637964020.png',
                'description' => 'Préparé à partir d\'agneau marocain grillé 100% fromage, sauce BBQ et mayonnaise, servi dans du pain frais grillé aux graines de sésame.',
                'price' => 35.0,
                'is_active' => 1,
                'level' => 1,
            ),
            98 =>
            array (
                'id' => 111,
                'category_id' => 14,
                'name' => 'triple manchegas',
                'image' => 'https://menu.soukexpress.ma/storage/items/576184e2-b611-47eb-9602-ed9dc1e03a37/1638024440.png',
                'description' => 'Trois Morceaux De Boeuf 100% Grillé Sur Flamme, Trois Tranches De Fromage Cheddar, Cornichons, Moutarde Et Sauce Tomate Sur Pain Aux Graines De Sésame Grillées',
                'price' => 75.0,
                'is_active' => 1,
                'level' => 1,
            ),
            99 =>
            array (
                'id' => 112,
                'category_id' => 36,
                'name' => 'poulet grillé sans os',
                'image' => 'https://menu.soukexpress.ma/storage/items/08e54137-2a6a-48cb-bc86-88cd9ec532f8/1638038346.jpg',
                'description' => 'poulet grillé tomates grillées oignons grillés Frette',
                'price' => 120.0,
                'is_active' => 1,
                'level' => 1,
            ),
            100 =>
            array (
                'id' => 113,
                'category_id' => 36,
                'name' => 'Quart de poulet grillé sur charbon de bois',
                'image' => 'https://menu.soukexpress.ma/storage/items/1cb808db-bd0c-4f51-9520-b045f48cc041/1638038470.png',
                'description' => 'tomates grillées oignons grillés Frette',
                'price' => 30.0,
                'is_active' => 1,
                'level' => 1,
            ),
            101 =>
            array (
                'id' => 114,
                'category_id' => 14,
                'name' => 'rodeo cheese manchegas',
                'image' => 'https://menu.soukexpress.ma/storage/items/d4ff4501-838d-4ce8-82c9-ff4729e8eac5/1638047014.png',
                'description' => 'Bœuf marocain grillé à la flamme, tranché de fromage garni de rondelles d\'oignon croquantes, saupoudré de mayonnaise et sauce BBQ, le tout sur un pain aux graines de sésame grillé',
                'price' => 40.0,
                'is_active' => 1,
                'level' => 1,
            ),
            102 =>
            array (
                'id' => 115,
                'category_id' => 28,
                'name' => 'Nuggets 3',
                'image' => 'https://menu.soukexpress.ma/storage/items/35edd4c6-abd2-4d04-b6d8-aab8ac84f97a/1638135232.png',
                'description' => 'Nuggets croustillants à base de poitrines de poulet 100% cuites dans de l\'huile de tournesol et de canola pour un meilleur goût doré.Choisissez parmi nos délicieuses sauces la sauce de votre choix',
                'price' => 10.0,
                'is_active' => 1,
                'level' => 1,
            ),
            103 =>
            array (
                'id' => 116,
                'category_id' => 28,
                'name' => 'Nuggets 6',
                'image' => 'https://menu.soukexpress.ma/storage/items/ce105c8d-3312-41b8-8a7d-1b0ad0f8f2bd/1638136662.png',
                'description' => 'Nuggets croustillants à base de poitrines de poulet 100% cuites dans de l\'huile de tournesol et de canola pour un meilleur goût doré.Choisissez parmi nos délicieuses sauces la sauce de votre choix',
                'price' => 20.0,
                'is_active' => 1,
                'level' => 1,
            ),
            104 =>
            array (
                'id' => 117,
                'category_id' => 28,
                'name' => 'Nuggets 10',
                'image' => 'https://menu.soukexpress.ma/storage/items/8046f232-ffd0-4d68-b75b-071e9cb973f0/1638139787.png',
                'description' => 'Nuggets croustillants à base de poitrines de poulet 100% cuites dans de l\'huile de tournesol et de canola pour un meilleur goût doré.Choisissez parmi nos délicieuses sauces la sauce de votre choix',
                'price' => 29.0,
                'is_active' => 1,
                'level' => 1,
            ),
            105 =>
            array (
                'id' => 118,
                'category_id' => 28,
                'name' => 'croquette de poisson par morceau',
                'image' => 'https://menu.soukexpress.ma/storage/items/33c1c9ff-43dd-4185-9035-5f3b040d1e95/1638142239.png',
                'description' => 'croquette de poisson',
                'price' => 5.0,
                'is_active' => 1,
                'level' => 1,
            ),
            106 =>
            array (
                'id' => 119,
                'category_id' => 28,
                'name' => 'Frites',
                'image' => 'https://menu.soukexpress.ma/storage/items/8287d294-4212-4b9e-bc14-d4b46f87bd1e/1638219731.png',
                'description' => 'Frites',
                'price' => 7.0,
                'is_active' => 1,
                'level' => 1,
            ),
            107 =>
            array (
                'id' => 120,
                'category_id' => 28,
                'name' => 'Cordon Blu',
                'image' => 'https://menu.soukexpress.ma/storage/items/111688f3-72fa-4b1c-b33b-92ab0d85ebec/1638225500.jpg',
                'description' => 'Cordon Blu',
                'price' => 12.0,
                'is_active' => 1,
                'level' => 1,
            ),
            108 =>
            array (
                'id' => 121,
                'category_id' => 28,
                'name' => 'Chicken Tenders par morceau',
                'image' => 'https://menu.soukexpress.ma/storage/items/cee00460-782b-478d-963e-0360c8bee627/1638226754.png',
                'description' => 'Chicken Tenders',
                'price' => 12.0,
                'is_active' => 1,
                'level' => 1,
            ),
            109 =>
            array (
                'id' => 122,
                'category_id' => 1,
                'name' => 'sandwich à la saucisse',
                'image' => 'https://menu.soukexpress.ma/storage/items/87c9a49a-ae1d-4607-8b3f-d784048281dc/1638301019.jpg',
                'description' => 'saucisse',
                'price' => 1.0,
                'is_active' => 1,
                'level' => 1,
            ),
            110 =>
            array (
                'id' => 123,
                'category_id' => 1,
                'name' => 'sandwich aux crevettes',
                'image' => 'https://menu.soukexpress.ma/storage/items/5c17fdd4-0873-4fc8-b925-cfa7d89491cc/1638301580.png',
                'description' => 'sandwich aux crevettes',
                'price' => 1.0,
                'is_active' => 1,
                'level' => 1,
            ),
            111 =>
            array (
                'id' => 124,
                'category_id' => 1,
                'name' => 'Sandwich aux fruits de mer',
                'image' => 'https://menu.soukexpress.ma/storage/items/72d0acc1-0468-47aa-8d06-ce34cd935605/1638301773.png',
                'description' => 'Salade au goût',
                'price' => 1.0,
                'is_active' => 1,
                'level' => 1,
            ),
            112 =>
            array (
                'id' => 126,
                'category_id' => 1,
                'name' => 'sandwich mixte',
                'image' => 'https://menu.soukexpress.ma/storage/items/82ec2bcc-348a-4d55-b49a-20c717bb9b4e/1638303872.jpg',
                'description' => 'mixte Salade au goût',
                'price' => 1.0,
                'is_active' => 1,
                'level' => 1,
            ),
            113 =>
            array (
                'id' => 127,
                'category_id' => 29,
                'name' => 'Un quart de poulet rôti',
                'image' => 'https://menu.soukexpress.ma/storage/items/0b17b1c6-d487-4cb8-ac40-f748773c48c3/1639157489.png',
                'description' => 'poulet salade le riz Frites',
                'price' => 25.0,
                'is_active' => 1,
                'level' => 1,
            ),
            114 =>
            array (
                'id' => 128,
                'category_id' => 29,
                'name' => 'Poulet à moitié rôti',
                'image' => 'https://menu.soukexpress.ma/storage/items/075e26b1-0ae3-4c4d-a94e-f982ae9959d3/1639159162.png',
                'description' => 'poulet salade le riz Frites',
                'price' => 45.0,
                'is_active' => 1,
                'level' => 1,
            ),
            115 =>
            array (
                'id' => 129,
                'category_id' => 29,
                'name' => 'poulet rôti entier',
                'image' => 'https://menu.soukexpress.ma/storage/items/0ef20364-f874-4f77-aeb1-c6eab132035b/1639164049.png',
                'description' => 'poulet salade le riz Frites',
                'price' => 90.0,
                'is_active' => 1,
                'level' => 3,
            ),
        ));


    }
}
